### ISSUE TITLE
Missing asyncio_amp.

### ISSUE THREAD

**Issue by Phrohdoh** [jonathanslenders/pymux#2]
```bash
(venv_pymux) ✓ ~/projects/python/pymux [master|…19] 
09:36 $ python --version && pip list && pymux
Python 3.4.3
asyncio (3.4.3)
docopt (0.6.2)
libpymux (0.1)
pip (6.1.1)
pymux (0.1)
pyte (0.4.9)
setuptools (15.0)
Traceback (most recent call last):
  File "/usr/local/bin/pymux", line 4, in <module>
    __import__('pkg_resources').run_script('pymux==0.1', 'pymux')
  File "/usr/local/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 729, in run_script
  File "/usr/local/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 1649, in run_script
  File "/usr/local/lib/python3.4/site-packages/pymux-0.1-py3.4.egg/EGG-INFO/scripts/pymux", line 21, in <module>
  File "/usr/local/lib/python3.4/site-packages/pymux-0.1-py3.4.egg/pymux/socket_client.py", line 5, in <module>
  File "/usr/local/lib/python3.4/site-packages/pymux-0.1-py3.4.egg/pymux/amp_commands.py", line 1, in <module>
ImportError: No module named 'asyncio_amp'
```

What else do I need to do to use pymux?

Thanks. :-)

**Comment by rmkraus** [comment]
This could be added to the setup.py by adding the URL to the zip download into the requires list.

It can also be installed by typing:
```
pip install https://github.com/jonathanslenders/asyncio-amp/archive/master.zip
```

**Comment by jonathanslenders** [comment]
Hi all,

The new version of pymux does not depend anymore on asyncio_amp. Just run ``pip install pymux`` on any Python version you want, and it should work.

Jonathan
