### ISSUE TITLE
Pyte 0.5.1: ImportError: cannot import name ctrl

### ISSUE THREAD

**Issue by livibetter** [jonathanslenders/pymux#31]
It seems there is some changes in Pyte, using 70d99014208ecea7e828690fb9d11dfc66beb59e.

```python
Traceback (most recent call last):
  File "/tmp/tpy/bin/pymux", line 9, in <module>
    load_entry_point('pymux==0.5', 'console_scripts', 'pymux')()
  File "/tmp/tpy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/tpy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2582, in load_entry_point
    return ep.load()
  File "/tmp/tpy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2265, in load
    return self._load()
  File "/tmp/tpy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2268, in _load
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/tpy/lib/python2.7/site-packages/pymux/entry_points/run_pymux.py", line 28, in <module>
    from pymux.main import Pymux
  File "/tmp/tpy/lib/python2.7/site-packages/pymux/main.py", line 17, in <module>
    from .arrangement import Arrangement, Pane, Window
  File "/tmp/tpy/lib/python2.7/site-packages/pymux/arrangement.py", line 11, in <module>
    from .process import Process
  File "/tmp/tpy/lib/python2.7/site-packages/pymux/process.py", line 14, in <module>
    from .stream import BetterStream
  File "/tmp/tpy/lib/python2.7/site-packages/pymux/stream.py", line 7, in <module>
    from pyte import ctrl
ImportError: cannot import name ctrl
```

**Comment by eas604** [comment]
@livibetter, sorry if I broke your environment. :) Although I'm not sure how.

What are your values for `$TMPDIR` and `$TMP`? In python, what is the output of:

    >>> import tempfile
    >>> tempfile.gettempdir()

**Comment by livibetter** [comment]
@eas604 I don't think it's Pymux, if I use **Pyte** 0.4.10, Pymux runs fine, Pyte 0.5.x was just released a few hours ago. So, I am pretty sure, it's Pyte.

But, I will still give you the information you asked, both environment variables are not set, as for in Python, that output is `/tmp`.

**Comment by eas604** [comment]
Ah, sorry, I mis-understood.

**Comment by jonathanslenders** [comment]
Fixed in https://github.com/jonathanslenders/pymux/commit/f3c94352f0b14002687bc9d1b7de20b323266e33

Thanks everyone. I pushed a new release.
