### ISSUE TITLE
AttributeError: 'BetterScreen' object has no attribute 'report_device_status'

### ISSUE THREAD

**Issue by ya790206** [jonathanslenders/pymux#35]
Crash when running vim

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymux/main.py", line 500, in run_server
    PipeInput(), DummyCallbacks())
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/eventloop/posix.py", line 150, in run 
    t() 
  File "/usr/local/lib/python2.7/dist-packages/pymux/process.py", line 280, in _read
    process()
  File "/usr/local/lib/python2.7/dist-packages/pymux/process.py", line 274, in process
    self.stream.feed(d)
  File "/usr/local/lib/python2.7/dist-packages/pymux/stream.py", line 51, in feed
    send(c)
  File "/usr/local/lib/python2.7/dist-packages/pymux/stream.py", line 157, in _parser_generator
    dispatch(csi[char], *params)
  File "/usr/local/lib/python2.7/dist-packages/pymux/stream.py", line 91, in dispatch
    getattr(listener, event)(*args, **flags)
AttributeError: 'BetterScreen' object has no attribute 'report_device_status'

**Comment by jonathanslenders** [comment]
Hi @ya790206,
Thanks for reporting! This went wrong after the last release of ``pyte``. I'll fix it asap.
Jonathan

**Comment by jonathanslenders** [comment]
Hi @ya790206,
This was fixed 8 days ago in https://github.com/jonathanslenders/pymux/commit/df949504b28fb73621a39552cd0fda3bdacafe10
I will do a new release soon.

**Comment by jonathanslenders** [comment]
(Don't hesitate to create a new issue if you find other bugs.)
