### ISSUE TITLE
Traceback upon opening: unexpected keyword argument 'errors'

### ISSUE THREAD

**Issue by JohnLunzer** [jonathanslenders/pymux#42]
I installed pymux from github clone taken at 11:55am ET April 30th 2016.

Traceback (most recent call last):
  File "/anaconda/bin/pymux", line 9, in <module>
    load_entry_point('pymux==0.9', 'console_scripts', 'pymux')()
  File "/anaconda/lib/python2.7/site-packages/pymux/entry_points/run_pymux.py", line 135, in run
    Client(socket_name).attach(true_color=true_color)
  File "/anaconda/lib/python2.7/site-packages/pymux/client.py", line 47, in __init__
    self._stdin_reader = PosixStdinReader(sys.stdin.fileno(), errors='replace')
TypeError: __init__() got an unexpected keyword argument 'errors'

**Comment by jonathanslenders** [comment]
Hi @JohnLunzer,

Thanks for reporting the issue!
Can you try again after cloning and installing the latest Git version from prompt-toolkit? The development of these two repositories goes hand in hand, so from time to time it doesn't work with the Pypi version of prompt-toolkit. Hopefully, I'll be able to push a new release of both soon.

Jonathan

**Comment by JohnLunzer** [comment]
Did the trick. Thanks for the _prompt_ response.
