### ISSUE TITLE
Bug:  ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by jonathanslenders** [jonathanslenders/pymux#59]
```
Traceback (most recent call last):
  File "/home/jonathan/git/pymux/pymux/main.py", line 538, in run_server
    PipeInput(), DummyCallbacks())
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 164, in run
    t()
  File "/home/jonathan/git/pymux/pymux/process.py", line 156, in done
    self.eventloop.remove_reader(self.master)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 289, in remove_reader
    self.selector.unregister(fd)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/eventloop/select.py", line 80, in unregister
    self._fds.remove(fd)
ValueError: list.remove(x): x not in list
```

**Comment by jonathanslenders** [comment]
```
Traceback (most recent call last):
  File "/home/jonathan/git/pymux/pymux/main.py", line 538, in run_server
    PipeInput(), DummyCallbacks())
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 164, in run
    t()
  File "/home/jonathan/git/pymux/pymux/server.py", line 70, in _recv
    self._process(self._recv_buffer[:pos])
  File "/home/jonathan/git/pymux/pymux/server.py", line 91, in _process
    self._inputstream.feed(packet['data'])
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/terminal/vt100_input.py", line 398, in feed
    self._input_parser.send(c)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/terminal/vt100_input.py", line 325, in _input_parser_generator
    self._call_handler(prefix[0], prefix[0])
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/terminal/vt100_input.py", line 340, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/home/jonathan/git/pymux/pymux/server.py", line 36, in feed_key
    self.cli.input_processor.process_keys()
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/key_binding/input_processor.py", line 201, in process_keys
    self._process_coroutine.send(key_press)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/key_binding/input_processor.py", line 158, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/key_binding/input_processor.py", line 228, in _call_handler
    handler.call(event)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/key_binding/registry.py", line 31, in call
    return self.handler(event)
  File "/home/jonathan/git/pymux/pymux/key_bindings.py", line 257, in key_handler
    call_command_handler(command, self.pymux, event.cli, arguments)
  File "/home/jonathan/git/pymux/pymux/commands/commands.py", line 93, in call_command_handler
    handler(pymux, cli, arguments)
  File "/home/jonathan/git/pymux/pymux/commands/commands.py", line 149, in command_wrapper
    func(pymux, cli, received_options)
  File "/home/jonathan/git/pymux/pymux/commands/commands.py", line 537, in copy_mode
    pane.enter_copy_mode()
  File "/home/jonathan/git/pymux/pymux/arrangement.py", line 103, in enter_copy_mode
    self._enter_scroll_buffer('Copy', document, get_tokens_for_line)
  File "/home/jonathan/git/pymux/pymux/arrangement.py", line 121, in _enter_scroll_buffer
    self.process.suspend()
  File "/home/jonathan/git/pymux/pymux/process.py", line 313, in suspend
    self.eventloop.remove_reader(self.master)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 289, in remove_reader
    self.selector.unregister(fd)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/eventloop/select.py", line 80, in unregister
    self._fds.remove(fd)
ValueError: list.remove(x): x not in list

```

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/pymux/commit/9c9363dd5ff89b09e05581177a6cdc51ba35dcf7
