### ISSUE TITLE
becomes unresponsive after `C-b .`

### ISSUE THREAD

**Issue by benatkin** [jonathanslenders/pymux#6]
I typed `C-b .` and rather than asking me which window position to move it to, giving an error, or doing nothing, it became unresponsive.

**Comment by jonathanslenders** [comment]
Hi @benatkin,

Thanks a lot for reporting this. It's a bug indeed. (Happens on Python 2 only.) I'll fix it asap.

```python
$ cat /tmp/pymux.crash 
Traceback (most recent call last):
  File "/home/jonathan/git/pymux/pymux/main.py", line 489, in run_server
    PipeInput(), DummyCallbacks())
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 150, in run
    t()
  File "/home/jonathan/git/pymux/pymux/server.py", line 55, in _recv
    self._process(self._recv_buffer[:pos])
  File "/home/jonathan/git/pymux/pymux/server.py", line 70, in _process
    self._inputstream.feed(packet['data'])
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/terminal/vt100_input.py", line 348, in feed
    self._input_parser.send(c)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/terminal/vt100_input.py", line 285, in _input_parser_generator
    self._call_handler(prefix[0], prefix[0])
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/terminal/vt100_input.py", line 300, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/home/jonathan/git/pymux/pymux/server.py", line 32, in <lambda>
    lambda key: self.cli.input_processor.feed_key(key))
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/key_binding/input_processor.py", line 172, in feed_key
    self._process_coroutine.send(key_press)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/key_binding/input_processor.py", line 144, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/key_binding/input_processor.py", line 187, in _call_handler
    handler.call(event)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/key_binding/registry.py", line 32, in call
    return self.handler(event)
  File "/home/jonathan/git/pymux/pymux/key_bindings.py", line 267, in key_handler
    call_command_handler(command, self.pymux, event.cli, arguments)
  File "/home/jonathan/git/pymux/pymux/commands/commands.py", line 93, in call_command_handler
    handler(pymux, cli, arguments)
  File "/home/jonathan/git/pymux/pymux/commands/commands.py", line 149, in command_wrapper
    func(pymux, cli, received_options)
  File "/home/jonathan/git/pymux/pymux/commands/commands.py", line 452, in command_prompt
    format_pymux_string(pymux, cli, variables['<default>'] or '')))
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/document.py", line 45, in __init__
    assert isinstance(text, six.text_type), 'Got %r' % text
AssertionError: Got ''
```

Jonathan

**Comment by jonathanslenders** [comment]
Hi @benatkin,

This should be fixed in the following commit: https://github.com/jonathanslenders/pymux/commit/41c3e76493ef646b77e108f3a0f632241001d992

I will try to push a new release ASAP.

Jonathan

**Comment by jonathanslenders** [comment]
A new release has been pushed to Pypi. Can you please try again?
