### ISSUE TITLE
AttributeError: 'BetterStream' object has no attribute 'percent'

### ISSUE THREAD

**Issue by sethwoodworth** [jonathanslenders/pymux#64]
I get this traceback when `pymux` is installed with python2.7 and python3.5.  This is on Debian Stretch.

It looks like `pyte`'s version 0.6.0 release removed `Stream.percent`.
+ [as of 0.5.1](https://github.com/selectel/pyte/blob/0.5.1/pyte/streams.py)
+ [as of 0.6.0](https://github.com/selectel/pyte/blob/0.6.0/pyte/streams.py)
```
Traceback (most recent call last):
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/main.py", line 538, in run_server
    PipeInput(), DummyCallbacks())
  File "/home/seth/.local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 164, in run
    t()
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/server.py", line 70, in _recv
    self._process(self._recv_buffer[:pos])
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/server.py", line 113, in _process
    self._create_cli(true_color=true_color, ansi_colors_only=ansi_colors_only, term=term)
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/server.py", line 157, in _create_cli
    self.cli = self.pymux.create_cli(self, output, input)
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/main.py", line 459, in create_cli
    self.create_window(cli, command=self.startup_command)
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/main.py", line 311, in create_window
    pane = self._create_pane(None, command, start_directory=start_directory)
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/main.py", line 283, in _create_pane
    has_priority=has_priority)
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/process.py", line 119, in from_command
    has_priority=has_priority)
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/process.py", line 85, in __init__
    self.stream = BetterStream(self.screen)
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/stream.py", line 36, in __init__
    self._validate_screen()
  File "/home/seth/.local/lib/python3.5/site-packages/pymux/stream.py", line 56, in _validate_screen
    for d in [self.basic, self.escape, self.sharp, self.percent, self.csi]:
AttributeError: 'BetterStream' object has no attribute 'percent'
```

**Comment by superbobry** [comment]
I think you can just swap `BetterStream` for `pyte.Stream` because the speed improvements are part of the 0.6.0 release.
