### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MakinWavz** [jonathanslenders/pymux#68]
Traceback (most recent call last):
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/main.py", line 538, in run_server
    PipeInput(), DummyCallbacks())
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 164, in run
    t()
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/server.py", line 70, in _recv
    self._process(self._recv_buffer[:pos])
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/server.py", line 113, in _process
    self._create_cli(true_color=true_color, ansi_colors_only=ansi_colors_only, term=term)
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/server.py", line 157, in _create_cli
    self.cli = self.pymux.create_cli(self, output, input)
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/main.py", line 459, in create_cli
    self.create_window(cli, command=self.startup_command)
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/main.py", line 311, in create_window
    pane = self._create_pane(None, command, start_directory=start_directory)
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/main.py", line 283, in _create_pane
    has_priority=has_priority)
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/process.py", line 119, in from_command
    has_priority=has_priority)
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/process.py", line 85, in __init__
    self.stream = BetterStream(self.screen)
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/stream.py", line 36, in __init__
    self._validate_screen()
  File "/home/chris/code/intacct_env/tornado/lib/python3.5/site-packages/pymux/stream.py", line 56, in _validate_screen
    for d in [self.basic, self.escape, self.sharp, self.percent, self.csi]:
AttributeError: 'BetterStream' object has no attribute 'percent'

**Comment by vasilishin** [comment]
Hi @MakinWavz, attribute `percent` was remove from Stream class in this [commit](https://github.com/selectel/pyte/commit/941f05c108648ba76a1e87827b1983f8f34f6041) and released in **pyte 0.6.0** version. You should check you installed pyte version and must be `pyte>=0.5.1,<0.6.0`.
